### ISSUE TITLE
Security issue in synapse 0.16.1

### ISSUE THREAD

**Issue by rrix** [ilianaw/dockerfiles#2]
[Security issue](https://matrix.org/blog/2016/07/08/critical-security-vulnerability-in-synapse-0-12-to-0-16-1-inclusive/) in synapse 0.16.1

**Comment by iliana** [comment]
:(

**Comment by iliana** [comment]
Updated in 157babd, pending build

**Comment by iliana** [comment]
Build: https://hub.docker.com/r/ianweller/synapse/builds/bz3agloybddkyvjrvjwfhkh/
